# Generated by Django 4.2 on 2023-04-17 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceAchat', '0002_remove_produit_image_produit_posologie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='produit',
        ),
    ]
