# Generated by Django 4.2 on 2023-04-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceAchat', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
            ],
        ),
    ]
