# Generated by Django 4.2 on 2023-04-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceAchat', '0005_produit2'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit2',
            name='prix',
            field=models.IntegerField(default=5000),
            preserve_default=False,
        ),
    ]
