# Generated by Django 4.2 on 2023-04-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceAchat', '0006_produit2_prix'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produit',
        ),
        migrations.AddField(
            model_name='produit2',
            name='posologie',
            field=models.CharField(default='lorem', max_length=500),
            preserve_default=False,
        ),
    ]
