# Generated by Django 4.2 on 2023-04-18 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceAchat', '0007_delete_produit_produit2_posologie'),
    ]

    operations = [
        migrations.CreateModel(
            name='apropos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
